//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic2.m
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorWorkTimeVW
    {
        public string fullname { get; set; }
        public int id { get; set; }
        public string date { get; set; }
        public string time { get; set; }
    }
}
