//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic2.m
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialVW1
    {
        public string name { get; set; }
        public string famliy { get; set; }
        public Nullable<int> Price { get; set; }
        public string title { get; set; }
        public int Id { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string fullname { get; set; }
        public string insurance { get; set; }
        public Nullable<int> MedicalRecordNum { get; set; }
        public string FilingDate { get; set; }
    }
}
