//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic2.m
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_desntistsWorkTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_desntistsWorkTime()
        {
            this.TBL_Appointment = new HashSet<TBL_Appointment>();
        }
    
        public int id { get; set; }
        public Nullable<int> DentistsId { get; set; }
        public Nullable<int> ClinicTimeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Appointment> TBL_Appointment { get; set; }
        public virtual TBL_ClinicDateTable TBL_ClinicDateTable { get; set; }
        public virtual TBL_doctors TBL_doctors { get; set; }
    }
}
