//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic2.m
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Images
    {
        public int Id { get; set; }
        public string title { get; set; }
        public byte[] picture { get; set; }
        public Nullable<int> patientID { get; set; }
    
        public virtual TBL_Patients TBL_Patients { get; set; }
    }
}
