//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic2.m
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Users()
        {
            this.TBL_Entrance = new HashSet<TBL_Entrance>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string Ncode { get; set; }
        public string BirthDay { get; set; }
        public string Address { get; set; }
        public string tell { get; set; }
        public string username { get; set; }
        public string Password { get; set; }
        public string resume { get; set; }
        public string gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Entrance> TBL_Entrance { get; set; }
    }
}
